---
title: 'covid-19'
author: "[Orhan Aktaş](https://www.linkedin.com/in/orhanaktas/)"
date: "25 Nov 2020"
output:
  html_document:
    theme: flatly
    df_print: paged
  pdf_document: default
  word_document: default
   
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```
Bu dökümanda ....


```{r}
library(tidyverse)
library(readxl)
url <- "https://bit.ly/2YAtytn"
destfile <- "X2YAtytn.xlsx"
curl::curl_download(url, destfile)


data <- read_excel(destfile) %>% select(c(3:12))

data<-data %>%
  rowwise %>% 
  mutate(
    min=min(c_across(defin_2015:defin_2019)),
    max=max(c_across(defin_2015:defin_2019)),
    avg=mean(c_across(defin_2015:defin_2019))
  ) %>% 
  ungroup %>% 
  mutate(
    dif = round(defin_2020 - avg, 2),
    Tarih = as.Date(tarih_2020)
  )
  
```

# Daily Deaths (2015-2019 Averages vs 2020)
 
```{r}

max_tarih<-data %>% filter(!is.na(son_guncelleme2020)) %>% select(tarih_2020) %>% summarise(max=max(tarih_2020)) 

data%>%
  mutate(avg=zoo::rollmean(avg,k=3,fill=NA),
         min=zoo::rollmean(min,k=3,fill=NA),
         max=zoo::rollmean(max,k=3,fill=NA)
         ) %>% 
  filter(Tarih < as.Date(max_tarih[[1]])-1 ) %>%
  ggplot(mapping = aes(x = Tarih)) +
  geom_ribbon(aes(ymin=min, ymax=max),fill="lightcyan3")+ 
  geom_line(aes(y = avg), color = "black") +
  geom_line(aes(y = defin_2020), color = "red") +
  scale_x_date(
    date_labels = "%b",
    date_breaks = "1 month"
  ) +
  
  geom_label(data = filter(data, Tarih == as.Date(max_tarih[[1]])-2 ), 
            aes(x=Tarih, y = defin_2020,label=format(Tarih,"%d/%m")), color = "black")+
  xlab("Ay")+
  ylab("Günlük Ölüm Sayısı")
```

# Excess Deaths (2015-2019 Averages vs 2020)

```{r}
data%>%
  mutate(avg=zoo::rollmean(avg,k=3,fill=NA),
         min=zoo::rollmean(min,k=3,fill=NA),
         max=zoo::rollmean(max,k=3,fill=NA)
         ) %>% 
  filter(Tarih < as.Date(max_tarih[[1]])-1 ) %>%
  ggplot(mapping = aes(x = Tarih)) +
  geom_line(aes(y = dif), color = "black") +
  scale_x_date(
    date_labels = "%b",
    date_breaks = "1 month"
  ) +
  
  geom_label(data = filter(data, Tarih == as.Date(max_tarih[[1]])-2 ), 
            aes(x=Tarih, y = dif,label=format(Tarih,"%d/%m")), color = "black")+
  xlab("Ay")+
  ylab("Günlük Fazladan Ölüm Sayısı")
```